### PR TITLE
Removing Windows 2012

### PR DESCRIPTION
**Pull request by uaag**
Removing Windows2012 form the different options. [MPCSUPENG-6914](https://rackspace.atlassian.net/browse/MPCSUPENG-6914)

### CODE REVIEW

**Review by jeffpatton1971 — APPROVED** [review]

**Comment by th31nitiate** [comment]
I cant tell if this is public repository or not but I should not be still getting notifications from this since I obviously haven't worked there for a year+ 

Can someone please help with getting these notifications disabled. I removed my self from the org which I assumed would of taking me of and repository subscriptions. Though I guess I was wrong.

**Comment by alexp789** [comment]
For fear of starting the classic…. This is a larger issue, as I’ve not worked at Rackspace for a whole lot longer and am getting them for some reason!

**Comment by alexp789** [comment]
To answer my own question: https://github.com/watching <https://github.com/watching>

**Review by stevengorrell — APPROVED** [review]

**Comment by stevengorrell** [comment]
Hey there! All the Terraform module repos in this org are public. To not get notified I believe you will have to remove yourself from the watch list.

**Pull request merged**
