### PR TITLE
Addition of ec2_os Ubuntu20

### PR DESCRIPTION
**Pull request by rajunandi91**
##### Summary of change(s):
- Added ubuntu20 ec2_os in the module for supporting of ubuntu 20 ec2 instance.

##### Reason for Change(s):

- While working on build I found that ubuntu20 was not supported for the variable ec2_os , So added the required changes to support ubuntu 20 ec2 OS.

##### If input variables or output variables have changed or has been added, have you updated the README? 
- Yes README is updated.

##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

### CODE REVIEW

**Review by twistedgrim — CHANGES_REQUESTED** [review]
Hello Raju,

It looks like a few things need changed in the PR here. Before I get to deep, Ill say Ive had it on my plate and most of the changes ready to push up in a commit if that would be better than you changing a bunch of items. Now that I know its needed imminently I can fast track those changes for you and possibly have it done tomorrow.

**Comment by rajunandi91** [comment]
Hello James,

Thanks for taking this up. Please go ahead.

Regards
Raju Nandi

**Comment by rajunandi91** [comment]
Hello James,

Can you please update on the current status.

Thanks
Raju Nandi

**Comment by twistedgrim** [comment]
Hello ubuntu 20.04 support has now been added https://github.com/rackspace-infrastructure-automation/aws-terraform-ec2_autorecovery/pull/84

**Pull request closed without merging**
